%% Create Group-Average Correlation Maps from Individual Subject Results
%
% This script loads the per-subject encoding accuracy (correlation) maps
% generated by 'run_encoding_pipeline.m', computes the average across all
% subjects, and saves the final group-level maps as both .mat and .dtseries.nii files.
%
% This should be run AFTER 'run_encoding_pipeline.m' has completed for all subjects.

clc; clear;
addpath(genpath('/local_raid1/202511_SW/01_software/HCPpipelines/global/matlab/cifti-matlab'));
addpath(genpath('/combinelab/01_software/toolboxes/cifti-matlab'));
addpath(genpath('/local_raid1/202511_SW/01_software/spm12'));
addpath(genpath('/local_raid1202511_SW/01_software/toolboxes/cifti-matlab'));

%% --- Configuration ---
% Define the feature types you want to process in this run.
% You can run this for one type at a time, or both.
FEATURE_TYPES_TO_PROCESS = {'Ahat', 'E'};

% --- Paths ---
% This should point to the parent directory where the 'Ahat' and 'E' result folders are.
BASE_SAVE_ROOT = '/combinelab/03_user/jungmin/01_project/01_Encoding/01_HWen_Encoding/PredNet/Titanic_trained/GUMP_test/encoding_analysis/original_prednet/500SUM_pretrain_result/four_train_four_test/layer4/';
CIFTI_TEMPLATE_FILE = '/combinelab2/03_user/jungmin/jungmin/02_data/01_Gump/01_FG_preprocessed/sub-01/sub-01_ciftify/ciftify/sub-01/MNINonLinear/Results_MNI152NLin2009cAsym/ses-movie_task-movie_run-1/ses-movie_task-movie_run-1_Atlas_s0.dtseries.nii';

% --- Analysis Parameters ---
subjects = {'sub-01', 'sub-02', 'sub-03', 'sub-04', 'sub-05', 'sub-06', 'sub-09', 'sub-10', 'sub-14', 'sub-15', 'sub-16', 'sub-17', 'sub-18', 'sub-19', 'sub-20'};

% Add CIFTI tools to path
addpath(genpath('/local_raid1/01_software/HCPpipelines/global/matlab/cifti-matlab'));

%% --- Main Group Averaging Loop ---
cii_template = ciftiopen(CIFTI_TEMPLATE_FILE, 'wb_command');

for t = 2 %:length(FEATURE_TYPES_TO_PROCESS)
    feature_type = FEATURE_TYPES_TO_PROCESS{t};
    fprintf('\n=================================================\n');
    fprintf('Processing Group Correlations for Feature Type: %s\n', feature_type);
    fprintf('=================================================\n');
    
    dataroot = fullfile(BASE_SAVE_ROOT, feature_type);
    
    all_subject_correlations = [];

    for subj_idx = 1:length(subjects)
        subject = subjects{subj_idx};
        corr_file = fullfile(dataroot, subject, 'average_correlations.mat');
        
        if exist(corr_file, 'file')
            fprintf('  Loading correlations for subject: %s\n', subject);
            loaded_data = load(corr_file);
            
            % Initialize the storage matrix on the first valid subject
            if isempty(all_subject_correlations)
                [num_layers, num_voxels] = size(loaded_data.final_corr_matrix);
                all_subject_correlations = nan(length(subjects), num_layers, num_voxels, 'single');
            end
            
            all_subject_correlations(subj_idx, :, :) = loaded_data.final_corr_matrix;
        else
            warning('  Missing correlation file for subject %s. Skipping.', subject);
        end
    end
    
    if isempty(all_subject_correlations)
        warning('No data found for feature type %s. Skipping group analysis.', feature_type);
        continue;
    end
    
    % Compute the group average by taking the mean across the first dimension (subjects)
    group_avg_corr_matrix = squeeze(nanmean(all_subject_correlations, 1)); % Result is [layers x voxels]
    
    fprintf('\n  Saving group-average correlation maps for %s...\n', feature_type);
    
    % Save as a .mat file
    save(fullfile(dataroot, ['group_average_correlations_', feature_type, '.mat']), 'group_avg_corr_matrix', '-v7.3');
    
    % Save as a .dtseries.nii file for visualization
    cii = cii_template;
    cii.cdata = group_avg_corr_matrix'; % Transpose to [voxels x layers]
    cii.diminfo{1, 1}.length = size(cii.cdata, 1);
    cii.diminfo{1, 2}.length = size(cii.cdata, 2);
    cii.diminfo{1, 1}.models(3:end) = [];
  
    cifti_save_path = fullfile(dataroot, ['group_average_correlations_', feature_type, '.dtseries.nii']);
    ciftisavereset(cii, cifti_save_path, 'wb_command');
    
    fprintf('  Group maps saved successfully.\n');
end

fprintf('\n--- All processing complete! ---\n');

